name: sipatka
description: Sistem Pembayaran SPP TK An-Naafi Nur
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.1.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  supabase_flutter: ^2.5.3
  provider: ^6.1.2
  intl: ^0.19.0
  url_launcher: ^6.3.0
  image_picker: ^1.1.2
  pdf: ^3.11.0 # Untuk generate PDF
  printing: ^5.12.0 # Untuk preview & print PDF

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:

  # Pastikan baris ini ada
  uses-material-design: true

  # Bagian assets
  assets:
    - assets/logo.png

  # Bagian fonts
  fonts:
    - family: Poppins
      fonts:
        - asset: fonts/Poppins-Regular.ttf
        - asset: fonts/Poppins-Bold.ttf
          weight: 700